version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/humhub
permissions:
  - object: /var/www/html/
    owner: www-data
    group: www-data
hooks:  
  ApplicationStop:
    - location: scripts/appstop.sh              
  Install:         
    - location: scripts/deploy.sh      
  AfterInstall:
    - location: scripts/appstart.sh
